# input shapefile downloaded from https://data.humdata.org/dataset/afg-admin-boundaries
admin:
  directory: afg_admbnda_adm2_agcho_20180522
  language: EN
mobility:
  scaling_factor:
    household_size: 8.0
    motor_vehicle_fraction: 0.027
vulnerability:
  ghs:
    column_row_pairs:
      - (23, 4)
      - (23, 5)
      - (24, 4)
      - (24, 5)
  ipc:
    filename: ~
  solid_fuels:
    # from https://www.who.int/nmh/countries/afg_en.pdf?ua=1
    frac_urban: 0.
    frac_rural: 0.
  handwashing_facilities:
    # from https://washdata.org/data/downloads#WLD
    frac_urban: 0.
    frac_rural: 0.
  # https://www.who.int/nmh/countries/afg_en.pdf?ua=1
  raised_blood_pressure: 0.
  # https://www.who.int/nmh/countries/afg_en.pdf?ua=1
  diabetes: 0.
  # https://vizhub.healthdata.org/tobacco/
  smoking: 0.
covid:
  url: ~
  filename: outputs-AFG v15_2 OCHA COMP2.csv
  header: 0
  skiprows: ~
  cases: True
  deaths: True
  individual_case_data: False
  cumulative: True
  admin_level: 0
  federal_state_dict: False
  # adm1_name_exp: ADM1_EN
  date_format: "%m/%d/%Y"
  replace_dict:
  hlx_dict:
    "baseline_predicted_reported": "#affected+infected+confirmed+total"
    "baseline_reportable_death": "#affected+infected+dead+total"
    "date": "#date"
contact_matrix:
  country: Pakistan
  file_number: 2
NPIs:
  url: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcZaUnsrDX5hVTfoGfbRZZRsuQetgotXjo4f7BdzNtWlMyq9b7Stg3XmLwfI69Q5nQ_Nj217qbTPx3/pub?gid=1114937196&single=true&output=csv

